export const rateProviderRateRevertRule = {
    agentType: 'blankAgentBuilder',
    agentName: 'Base - getRate health check',
    state: 'enabled',
    rule: {
        chain: 'ethereum',
        triggerType: 'time_based_trigger',
        severity: 'medium',
        contractAddress: '0x0000000000000000000000000000000000000000',
        involvedAssets: {},
        secrets: {},
        input: [],
        inputDataType: [],
        outputDataType: [],
        idlJson: {},
        abi: {},
        contractFunctionObject: {},
        outputIndex: '',
        funcSig: '',
        time_based_trigger: {
            type: 'time_based_trigger',
            severity: 'medium',
            period: 1,
            period_unit: 'blocks',
            chain: 'ethereum',
        },
        typeIds: [],
        fileName: 'some_file_name.json',
        operands: [],
        operator: '',
        data_retention_required: false,
        conditions: [
            {
                output_index: '',
                operator: '',
                operands: [],
            },
            {
                operator: 'formula',
                output_index: '',
                operands: [
                    {
                        variable_extraction: [
                            {
                                type: 'context',
                                output_index: 'block_timestamp',
                                var_name: 'block_timestamp',
                            },
                            {
                                type: 'context',
                                output_index: 'block_number',
                                var_name: 'block_number',
                            },
                            {
                                type: 'context',
                                output_index: 'chain',
                                var_name: 'chain',
                            },
                            {
                                type: 'gcr',
                                contract_address: '0x0000000000000000000000000000000000000000',
                                operands: [],
                                operator: 'nop',
                                block_offset: 0,
                                input: [],
                                input_data_type: [],
                                output_data_type: ['uint256'],
                                output_index: 'output_arg_0',
                                func_sig: 'getRate()',
                                chain: 'ethereum',
                                var_name: 'getRateOutput',
                                contract_function_object: null,
                                idl_json: null,
                                abi_string: null,
                                type_arguments: [],
                                generic_type_params: [],
                            },
                            {
                                type: 'gcr',
                                contract_address: '0x0000000000000000000000000000000000000000',
                                operands: [],
                                operator: 'nop',
                                block_offset: -25,
                                input: [],
                                input_data_type: [],
                                output_data_type: ['uint256'],
                                output_index: 'output_arg_0',
                                func_sig: 'getRate()',
                                chain: 'ethereum',
                                var_name: 'getRateOutput_1',
                                contract_function_object: null,
                                idl_json: null,
                                abi_string: null,
                                type_arguments: [],
                                generic_type_params: [],
                            },
                            {
                                type: 'gcr',
                                contract_address: '0x0000000000000000000000000000000000000000',
                                operands: [],
                                operator: 'nop',
                                block_offset: -50,
                                input: [],
                                input_data_type: [],
                                output_data_type: ['uint256'],
                                output_index: 'output_arg_0',
                                func_sig: 'getRate()',
                                chain: 'ethereum',
                                var_name: 'getRateOutput_2',
                                contract_function_object: null,
                                idl_json: null,
                                abi_string: null,
                                type_arguments: [],
                                generic_type_params: [],
                            },
                            {
                                type: 'json_processing',
                                json_path: 'Z2V0UmF0ZU91dHB1dD1udWxsID8gMTowZ2V0UmF0ZU91dHB1dF8xPW51bGwgPyAxOjBnZXRSYXRlT3V0cHV0XzI9bnVsbCA/IDE6MA==',
                                var_name: 'is_null',
                                json_path_engine: 'jsonata',
                            },
                            {
                                type: 'json_processing',
                                json_path: 'aXNfbnVsbCA9IHRydWU=',
                                var_name: 'condition_0',
                                json_path_engine: 'jsonata',
                            },
                        ],
                        eval: {
                            sym_expression: 'condition_0',
                            operator: 'compare_exact',
                            operands: [true],
                            custom_description: '',
                        },
                    },
                ],
            },
        ],
        isReminderEnabled: false,
        module: '',
        moduleName: '',
        typeArguments: [],
        genericTypeParams: [],
        advanced: ['customDescription'],
        customDescription: '',
        ruleString: '',
    },
    severity: 'Medium',
    muteDuration: 0,
    channelsConfigurations: [
        {
            id: 2451,
            name: 'rate-provider-alerts',
        },
    ],
    remindersConfigurations: [],
    endAlertsOption: 'sameAsStart',
    endAlertsConfigurations: [],
    delay: 600,
    securitySuitIds: [1373],
    graphData: {
        edges: [
            {
                id: 'xy-edge__76ad1bf3-1f12-45d9-a28e-043fd99d0ca8-07b6cf44-db10-47b8-8a89-5c2b43d775e6',
                source: '76ad1bf3-1f12-45d9-a28e-043fd99d0ca8',
                target: '07b6cf44-db10-47b8-8a89-5c2b43d775e6',
            },
            {
                id: 'xy-edge__6aecd52f-8b2f-49f5-9707-12952ef36557-b6d012b6-03e1-4295-9389-a2288fbfb211',
                source: '6aecd52f-8b2f-49f5-9707-12952ef36557',
                target: 'b6d012b6-03e1-4295-9389-a2288fbfb211',
            },
            {
                id: 'xy-edge__07b6cf44-db10-47b8-8a89-5c2b43d775e6-87aaa6f8-24f8-47f1-9a59-da2d150d4976',
                source: '07b6cf44-db10-47b8-8a89-5c2b43d775e6',
                target: '87aaa6f8-24f8-47f1-9a59-da2d150d4976',
            },
            {
                id: 'xy-edge__87aaa6f8-24f8-47f1-9a59-da2d150d4976-567e4cf6-ab82-43e1-a47c-1e70abf2d99a',
                source: '87aaa6f8-24f8-47f1-9a59-da2d150d4976',
                target: '567e4cf6-ab82-43e1-a47c-1e70abf2d99a',
            },
            {
                id: 'xy-edge__567e4cf6-ab82-43e1-a47c-1e70abf2d99a-6c41586c-ced7-4db6-86cb-fe2f85f73f9e',
                source: '567e4cf6-ab82-43e1-a47c-1e70abf2d99a',
                target: '6c41586c-ced7-4db6-86cb-fe2f85f73f9e',
            },
            {
                id: 'xy-edge__6c41586c-ced7-4db6-86cb-fe2f85f73f9e-6aecd52f-8b2f-49f5-9707-12952ef36557',
                source: '6c41586c-ced7-4db6-86cb-fe2f85f73f9e',
                target: '6aecd52f-8b2f-49f5-9707-12952ef36557',
            },
        ],
        nodes: [
            {
                id: '76ad1bf3-1f12-45d9-a28e-043fd99d0ca8',
                data: {
                    type: 'blocks',
                    chain: 'ethereum',
                    amount: 1,
                },
                type: 'time-based-node',
                measured: {
                    width: 158,
                    height: 107,
                },
                position: {
                    x: 907.4151541834707,
                    y: -320.85313137566,
                },
            },
            {
                id: '07b6cf44-db10-47b8-8a89-5c2b43d775e6',
                data: {
                    alias: 'getRateOutput',
                    chain: 'ethereum',
                    input: [],
                    funcSig: 'getRate()',
                    aliasType: 'uint256',
                    moduleName: '',
                    blockOffset: 0,
                    description: '',
                    outputIndex: 0,
                    inputDataType: [],
                    outputDataType: ['uint256'],
                    contractAddress: '0x0000000000000000000000000000000000000000',
                    genericTypeParams: [],
                    contractAddressAlias: '0x0000000000000000000000000000000000000000',
                    contractFunctionObject: {
                        name: 'getRate',
                        type: 'function',
                        inputs: [],
                        funcSig: 'getRate()',
                        outputs: [
                            {
                                name: '',
                                type: 'uint256',
                                internalType: 'uint256',
                            },
                        ],
                        stateMutability: 'view',
                    },
                },
                type: 'read-contract-node',
                measured: {
                    width: 269,
                    height: 341,
                },
                position: {
                    x: 710,
                    y: -98,
                },
            },
            {
                id: '6c41586c-ced7-4db6-86cb-fe2f85f73f9e',
                data: {
                    alias: 'is_null',
                    formula: '{{getRateOutput}}=null ? 1:0\n{{getRateOutput_1}}=null ? 1:0\n{{getRateOutput_2}}=null ? 1:0',
                    aliasType: 'boolean',
                    description: '',
                },
                type: 'calculation-node',
                measured: {
                    width: 269,
                    height: 157,
                },
                position: {
                    x: 858.058774303253,
                    y: 329.7940661597082,
                },
            },
            {
                id: '6aecd52f-8b2f-49f5-9707-12952ef36557',
                data: {
                    valueA: 'is_null',
                    valueB: 'true',
                    condition: 'compare_exact',
                    description: '',
                    valueAMultiplier: 0,
                    valueBMultiplier: 0,
                    valueCMultiplier: 0,
                },
                type: 'condition-node',
                measured: {
                    width: 269,
                    height: 92,
                },
                position: {
                    x: 1277.5362790426132,
                    y: 334.06790786568956,
                },
            },
            {
                id: 'b6d012b6-03e1-4295-9389-a2288fbfb211',
                data: {
                    message: '',
                    description: '',
                },
                type: 'send-alert-node',
                measured: {
                    width: 269,
                    height: 87,
                },
                position: {
                    x: 1277.536571118261,
                    y: 478.30474714902357,
                },
            },
            {
                id: '87aaa6f8-24f8-47f1-9a59-da2d150d4976',
                data: {
                    alias: 'getRateOutput_1',
                    chain: 'ethereum',
                    input: [],
                    funcSig: 'getRate()',
                    aliasType: 'uint256',
                    moduleName: '',
                    blockOffset: 25,
                    description: '',
                    outputIndex: 0,
                    inputDataType: [],
                    outputDataType: ['uint256'],
                    contractAddress: '0x0000000000000000000000000000000000000000',
                    genericTypeParams: [],
                    contractAddressAlias: '0x0000000000000000000000000000000000000000',
                    contractFunctionObject: {
                        name: 'getRate',
                        type: 'function',
                        inputs: [],
                        funcSig: 'getRate()',
                        outputs: [
                            {
                                name: '',
                                type: 'uint256',
                                internalType: 'uint256',
                            },
                        ],
                        stateMutability: 'view',
                    },
                },
                type: 'read-contract-node',
                measured: {
                    width: 269,
                    height: 341,
                },
                position: {
                    x: 1032.2185887768808,
                    y: -92.72228338293468,
                },
            },
            {
                id: '567e4cf6-ab82-43e1-a47c-1e70abf2d99a',
                data: {
                    alias: 'getRateOutput_2',
                    chain: 'ethereum',
                    input: [],
                    funcSig: 'getRate()',
                    aliasType: 'uint256',
                    moduleName: '',
                    blockOffset: 50,
                    description: '',
                    outputIndex: 0,
                    inputDataType: [],
                    outputDataType: ['uint256'],
                    contractAddress: '0x0000000000000000000000000000000000000000',
                    genericTypeParams: [],
                    contractAddressAlias: '0x0000000000000000000000000000000000000000',
                    contractFunctionObject: {
                        name: 'getRate',
                        type: 'function',
                        inputs: [],
                        funcSig: 'getRate()',
                        outputs: [
                            {
                                name: '',
                                type: 'uint256',
                                internalType: 'uint256',
                            },
                        ],
                        stateMutability: 'view',
                    },
                },
                type: 'read-contract-node',
                measured: {
                    width: 269,
                    height: 341,
                },
                position: {
                    x: 1348.5407460279084,
                    y: -89.07579005409917,
                },
            },
        ],
        description: '',
    },
    mode: 'onchain',
}
