export const erc4626Template = `
# Rate Provider: {{erc4626}} rate provider

## Details
This report was autogenerated on {{date}}.

- Deployed at:
    - [{{network}}:{{erc4626Address}}]({{chainExplorer}})
- Audit report(s):
    - [Audits]({{linkToAudits}})

## Context
{{erc4626Docs}}

## Review Checklist: Bare Minimum Compatibility
Each of the items below represents an absolute requirement for the Rate Provider. If any of these is unchecked, the Rate Provider is unfit to use.

- [{{hasPassingForkTests}}] Tests based on the [balancer-v3-monorepo](https://github.com/balancer/balancer-v3-monorepo/tree/main/pkg/vault/test/foundry/fork) pass for the given ERC4626 vaults, which can be found [here](https://github.com/balancer/balancer-v3-erc4626-tests/tree/main/test).
- [{{hasRequiredFunctionsImplemented}}] The required Vault implements the required operational ERC4626 Interface

### Administrative Privileges
- [{{isUpgradeable}}] The ERC4626 Vault is upgradeable** (e.g., via a proxy architecture).
- [{{hasUpgradeableElements}}] Other contracts which are part of the \`mint\` callchain are upgradeable**. You can find more information
   about the involved contracts in this [tenderly simulation]({{tenderlySimUrl}})

## Conclusion
**Summary judgment: {{usableUnusable}}**
Passing fork tests can be found at {{linkToForkTests}}.

** upgradeable in this context means that:
- The contract is a proxy contract with an implementation sourced from Etherscan.
    
`
