name: create review
on:
  issues:
    types: [opened, edited, reopened]
jobs:
  write-review:
    runs-on: ubuntu-latest
    steps:
      - name: Parse Issue
        id: parse-issue
        uses: GrantBirki/issue-template-parser@v7.0.4
        with:
          body: ${{ github.event.issue.body }}
      - name: process issue content
        id: process-issue
        run: npx tsx scripts/process-issue.ts '${{ steps.parse-issue.outputs.json }}'
