name: create review
on:
  issues:
    types: [opened, edited, reopened]
jobs:
  write-review:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Install dependencies
        run: npm install

      - name: Parse Issue
        id: parse-issue
        uses: GrantBirki/issue-template-parser@v7.0.4
        with:
          body: ${{ github.event.issue.body }}

      - name: Process issue content
        id: process-issue
        run: npx tsx scripts/process-issue.ts
        env:
          ISSUE_DATA: ${{ steps.parse-issue.outputs.json }}
          TENDERLY_ACCOUNT_SLUG: ${{ secrets.TENDERLY_ACCOUNT_SLUG }}
          TENDERLY_PROJECT_SLUG: ${{ secrets.TENDERLY_PROJECT_SLUG }}
          TENDERLY_API_ACCESS_KEY: ${{ secrets.TENDERLY_API_ACCESS_KEY }}
          ETHERSCAN_API_KEY: ${{ secrets.ETHERSCAN_API_KEY }}
          BASE_RPC_URL: ${{ secrets.BASE_RPC_URL }}
          MAINNET_RPC_URL: ${{ secrets.MAINNET_RPC_URL }}
          ARBITRUM_RPC_URL: ${{ secrets.ARBITRUM_RPC_URL }}
          AVALANCHE_RPC_URL: ${{ secrets.AVALANCHE_RPC_URL }}
          GNOSIS_RPC_URL: ${{ secrets.GNOSIS_RPC_URL }}
          FRAXTAL_RPC_URL: ${{ secrets.FRAXTAL_RPC_URL }}
          OPTIMISM_RPC_URL: ${{ secrets.OPTIMISM_RPC_URL }}
          SONIC_RPC_URL: ${{ secrets.SONIC_RPC_URL }}
          HYPEREVM_RPC_URL: ${{ secrets.HYPEREVM_RPC_URL }}
          HYPERNATIVE_CLIENT_ID: ${{ secrets.HYPERNATIVE_CLIENT_ID }}
          HYPERNATIVE_CLIENT_SECRET: ${{ secrets.HYPERNATIVE_CLIENT_SECRET }}

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v7.0.8
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: review/issue-${{ github.event.issue.number }}
          base: main
          title: "Review: Rate Provider from Issue #${{ github.event.issue.number }}"
          body: |
            ## Automated Review Generated

            This PR was automatically generated from issue #${{ github.event.issue.number }}.

            **Network:** `${{ fromJson(steps.parse-issue.outputs.json).network }}`
            **Rate Provider:** `${{ fromJson(steps.parse-issue.outputs.json).rate_provider_contract_address }}`
            **Asset Contract:** `${{ fromJson(steps.parse-issue.outputs.json).asset_contract_address }}`

            ### Generated Files:
            - Rate provider review documentation
            - Updated registry files

            Closes #${{ github.event.issue.number }}
          labels: |
            automated-review
            rate-provider
          assignees: mkflow27
