name: registry format validation
on:
  pull_request:
    types: [opened, synchronize]
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install dependencies
        run: npm install
      - name: Debug env vars
        run: |
          echo "ETHERSCAN_API_KEY is set: ${{ env.ETHERSCAN_API_KEY != '' }}"
        env:
          ETHERSCAN_API_KEY: ${{ env.ETHERSCAN_API_KEY }}
      - name: Validate registry format
        run: npm run test
        env:
          ETHERSCAN_API_KEY: ${{ env.ETHERSCAN_API_KEY }}
